#!/usr/bin/env python2.6

# Python script to automate creation and configuration of new SVN repos.
#	
# Author: Chase McManning

import argparse, os

# Build and configure a new SVN Repository, adding the specific user as the owner
def create_new_repo(title, repo):
	os.system('svnadmin create /home/arcdev/svn/' + repo)
	add_to_repo_list(title, repo)
	write_repo_passwd(repo)
	write_svnserve_conf(repo)
	print 'Finished setting up ' + title

def write_repo_passwd(repo):
	fn = '/home/arcdev/svn/' +  repo +  '/conf/passwd'
	with open(fn, 'w') as fp:
		fp.write('# Generated by Python script.\n')
		fp.write('[users]\n')

	# Fix permissions to allow PHP to screw with it
	os.system('chmod 666 /home/arcdev/svn/' +  repo +  '/conf/passwd')
	print 'Wrote ' + fn
	
def write_svnserve_conf(repo):
	fn = '/home/arcdev/svn/' + repo + '/conf/svnserve.conf'
	with open(fn, 'w') as fp:
		fp.write('[general]\n')
		fp.write('anon-access = none\n')
		fp.write('auth-access = write\n')
		fp.write('password-db = passwd\n')
		# fp.write('realm = SOME_REALM')
		fp.write('[sasl]\n') # TODO: Line necessary?
	print 'Wrote ' + fn

def add_to_repo_list(title, repo):
	fn = '/home/arcdev/svn/repos.ini'
	exists = os.path.isfile(fn)
	with open(fn, 'a') as fp:
		if exists == False:
			fp.write('[repos]\n')
		fp.write(repo + ' = "' + title + '"\n')
	if exists == False:
		os.system('chmod 666 ' + fn)
	print 'Added ' + title + ' (' + repo + ') to repos.ini'

parser = argparse.ArgumentParser()

parser.add_argument('--repo', '-r', action='store', dest='repo', help='Repo subdirectory name')
parser.add_argument('--title', '-t', action='store', dest='title', help='Title to display in WebSVN')

results = parser.parse_args()

if results.repo != None:
	if results.title == None:
		results.title = results.repo

	create_new_repo(results.title, results.repo)
	
else:
	print 'Arguments required. Use --help bro'

